export const projects = [
  {
    id: 0,
    img: "./img/watches.jpg",
    top: true,
    recent: false,
    react: true,
    vanilla: false,
    angular: false,
    axios: true,
    code: "https://github.com/Bryang09/watches",
    demo: "https://intense-bayou-29884.herokuapp.com/#/",
    name: "The Watches App",
    desc: `This is an application created with the MERN Stack.`
  },
  {
    id: 1,
    img: "./img/newshelter.jpg",
    top: true,
    recent: false,
    react: true,
    vanilla: false,
    angular: false,
    axios: true,
    code: "https://github.com/Bryang09/newshelter",
    demo: "https://bryang09.github.io/newshelter/#/",
    name: "The Shelter App",
    desc: `This is a React application that uses the PetFinder API to search for nearby shelters and animals.`
  },
  {
    id: 2,
    img: "./img/newmovies.jpg",
    top: true,
    recent: false,
    react: true,
    vanilla: false,
    angular: false,
    axios: true,
    code: "https://github.com/Bryang09/newmovies",
    demo: "https://bryang09.github.io/newmovies/#/",
    name: "The Movies App",
    desc: `This is an application that uses the MoviesDB API to search for movies and shows.`
  },
  {
    id: 3,
    img: "./img/anime.jpg",
    top: true,
    recent: false,
    react: true,
    vanilla: false,
    angular: false,
    axios: true,
    code: "https://github.com/Bryang09/anime",
    demo: "https://bryang09.github.io/anime/#/",
    name: "The Watches App",
    desc: `This is an application created with the MERN Stack.`
  },
  {
    id: 4,
    img: "./img/traveling.jpg",
    top: true,
    recent: false,
    react: true,
    vanilla: false,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/traveling",
    demo: "https://bryang09.github.io/traveling/#/",
    name: "The Traveling App",
    desc: `This is an application created with React that focuses on better animations and UI`
  },
  {
    id: 5,
    img: "./img/ng-restaurant.jpg",
    top: true,
    recent: false,
    react: false,
    vanilla: false,
    angular: true,
    axios: false,
    code: "https://github.com/Bryang09/ng-restaurant",
    demo: "https://bryang09.github.io/ng-restaurant",
    name: "The Restuarant App",
    desc: `This is an application that uses Angular 7 to display different menu items.`
  },
  {
    id: 6,
    img: "./img/designer.jpg",
    top: false,
    recent: true,
    react: false,
    vanilla: true,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/appDeveloper",
    demo: "https://bryang09.github.io/appDeveloper",
    name: "The Designer App",
    desc: `This is a Vanilla Js application created after prototyping the design with Adobe XD`
  },
  {
    id: 7,
    img: "./img/construction.jpg",
    top: false,
    recent: true,
    react: false,
    vanilla: true,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/construction",
    demo: "https://bryang09.github.io/construction",
    name: "The Construction App",
    desc: `This is a Vanilla Js Application for a fictional construction company.`
  },
  {
    id: 8,
    img: "./img/speech.jpg",
    top: false,
    recent: true,
    react: false,
    vanilla: true,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/textToSpeech2",
    demo: "https://bryang09.github.io/textToSpeech2",
    name: "The Speech App",
    desc: `A Vanilla Js application which speaks.`
  },
  {
    id: 9,
    img: "./img/word.jpg",
    top: false,
    recent: true,
    react: false,
    vanilla: true,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/wordBeater",
    demo: "https://bryang09.github.io/wordBeater",
    name: "The Word Game",
    desc: `This is a Vanilla Js Application that tests typing speed.`
  },
  {
    id: 10,
    img: "./img/split.jpg",
    top: false,
    recent: true,
    react: false,
    vanilla: true,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/splitScreen",
    demo: "https://bryang09.github.io/splitScreen",
    name: "The Split Screen App",
    desc: `This is an application that changes display based on mouse position.`
  },
  {
    id: 11,
    img: "./img/ghFinder.jpg",
    top: false,
    recent: true,
    react: false,
    vanilla: true,
    angular: false,
    axios: false,
    code: "https://github.com/Bryang09/ghFinder",
    demo: "https://bryang09.github.io/ghFinder",
    name: "The GhFinder App",
    desc: `A Vanilla Js application that uses the Github Api.`
  },
  {
    id: 12,
    img: "./img/glasses.png",
    top: false,
    recent: false,
    react: false,
    vanilla: false,
    angular: true,
    axios: false,
    code: "https://github.com/Bryang09/ng-glasses",
    demo: "https://bryang09.github.io/ng-glasses",
    name: "The Glasses App",
    desc: `A UI centric application that uses Angular.`
  },
  {
    id: 13,
    img: "./img/trainer.png",
    top: false,
    recent: false,
    react: false,
    vanilla: false,
    angular: true,
    axios: false,
    code: "https://github.com/Bryang09/ng-trainer",
    demo: "https://bryang09.github.io/ng-trainer",
    name: "The Trainer App",
    desc: `This is an application for a for a fiction trainer.`
  }
];
